apiVersion: v1
kind: ConfigMap
metadata:
  name: crisissync-config
data:
  KAFKA_BROKERS: kafka:29092
  MONGO_URI: mongodb://mongo:27017/crisissync
  FRONTEND_ORIGIN: "*"
  GEMINI_MODEL: gemini-1.5-flash
